site_name: 资本论
repo_url: https://github.com/bowenEI/das-capital

# Configuration
theme:
  name: material
  # custom_dir: build/overrides
  language: zh
  features:
    # - announce.dismiss
    - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: white
      # accent: indigo
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      # accent: indigo
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
  font:
    text: Noto Sans SC
    code: Fira Code
  favicon: assets/images/favicon.png
  logo: assets/images/marx.png
  icon:
    logo: logo
    repo: fontawesome/brands/github
    edit: material/file-edit-outline

nav:
  - '欢迎': 'index.md'
  - '第一卷 资本的生产过程':
    - './part1/index.md'
    - '序言和跛':
      - '第一版序言': './part1/pref/p1.md'
      - '第二版跛': './part1/pref/p2.md'
      - '法文版序言和跋': './part1/pref/p3.md'
      - '第三版序言': './part1/pref/p4.md'
      - '英文版序言': './part1/pref/p5.md'
      - '第四版序言': './part1/pref/p6.md'
    - '第一篇 商品和货币':
      - './part1/ch1/index.md'
      - '第一章 商品': './part1/ch1/sec1.md'
      - '第二章 交换过程': './part1/ch1/sec2.md'
      - '第三章 货币或商品流通': './part1/ch1/sec3.md'
    - '第二篇 货币转化为资本':
      - './part1/ch2/index.md'
      - '第四章 货币转化为资本': './part1/ch2/sec4.md'
    - '第三篇 绝对剩余价值的生产':
      - './part1/ch3/index.md'
      - '第五章 劳动过程和价值增殖过程': './part1/ch3/sec5.md'
      - '第六章 不变资本和可变资本': './part1/ch3/sec6.md'
      - '第七章 剩余价值率': './part1/ch3/sec7.md'
      - '第八章 工作日': './part1/ch3/sec8.md'
      - '第九章 剩余价值率和剩余价值量': './part1/ch3/sec9.md'
    - '第四篇 相对剩余价值的生产':
      - './part1/ch4/index.md'
      - '第十章 相对剩余价值的概念': './part1/ch4/sec10.md'
      - '第十一章 协作': './part1/ch4/sec11.md'
      - '第十二章 分工和工场手工业': './part1/ch4/sec12.md'
      - '第十三章 机器和大工业': './part1/ch4/sec13.md'
    - '第五篇 绝对剩余价值和相对剩余价值的生产':
      - './part1/ch5/index.md'
      - '第十四章 绝对剩余价值和相对剩余价值': './part1/ch5/sec14.md'
      - '第十五章 劳动力价格和剩余价值的量的变化': './part1/ch5/sec15.md'
      - '第十六章 剩余价值率的各种公式': './part1/ch5/sec16.md'
    - '第六篇 工资':
      - './part1/ch6/index.md'
      - '第十七章 劳动力的价值或价格转化为工资': './part1/ch6/sec17.md'
      - '第十八章 计时工资': './part1/ch6/sec18.md'
      - '第十九章 计件工资': './part1/ch6/sec19.md'
      - '第二十章 工资的国民差异': './part1/ch6/sec20.md'
    - '第七篇 资本积累的过程':
      - './part1/ch7/index.md'
      - '第二十一章 简单再生产': './part1/ch7/sec21.md'
      - '第二十二章 剩余价值转化为资本': './part1/ch7/sec22.md'
      - '第二十三章 资本主义积累的一般规律': './part1/ch7/sec23.md'
      - '第二十四章 所谓原始积累': './part1/ch7/sec24.md'
      - '第二十五章 现代殖民理论': './part1/ch7/sec25.md'
  - '第二卷 资本的流通过程':
    - './part2/index.md'
    - '序言和跛':
      - '序言': './part2/pref/p1.md'
      - '第二版序言': './part2/pref/p2.md'
    - '第一篇 资本形态变化及其循环':
      - './part2/ch1/index.md'
      - '第一章 货币资本的循环': './part2/ch1/sec1.md'
      - '第二章 生产资本的循环': './part2/ch1/sec2.md'
      - '第三章 商品资本的循环': './part2/ch1/sec3.md'
      - '第四章 循环过程的三个公式': './part2/ch1/sec4.md'
      - '第五章 流通时间': './part2/ch1/sec5.md'
      - '第六章 流通费用': './part2/ch1/sec6.md'
    - '第二篇 资本周转':
      - './part2/ch2/index.md'
      - '第七章 周转时间和周转次数': './part2/ch2/sec7.md'
      - '第八章 固定资本和流动资本': './part2/ch2/sec8.md'
      - '第九章 预付资本的总周转。周转的周期': './part2/ch2/sec9.md'
      - '第十章 关于固定资本和流动资本的理论。重农学派和亚当·斯密': './part2/ch2/sec10.md'
      - '第十一章 关于固定资本和流动资本的理论。李嘉图': './part2/ch2/sec11.md'
      - '第十二章 劳动期间': './part2/ch2/sec12.md'
      - '第十三章 生产时间': './part2/ch2/sec13.md'
      - '第十四章 流通时间': './part2/ch2/sec14.md'
      - '第十五章 周转时间对预付资本量的影响': './part2/ch2/sec15.md'
      - '第十六章 可变资本的周转': './part2/ch2/sec16.md'
      - '第十七章 剩余价值的流通': './part2/ch2/sec17.md'
    - '第三篇 社会总资本的再生产和流通':
      - './part2/ch3/index.md'
      - '第十八章 导言': './part2/ch3/sec18.md'
      - '第十九章 前人对这个问题的阐述': './part2/ch3/sec19.md'
      - '第二十章 简单再生产': './part2/ch3/sec20.md'
      - '第二十一章 积累和扩大再生产': './part2/ch3/sec21.md'
  - '第三卷 资本主义生产总过程':
    - './part3/index.md'
    - '上册':
      - '第一篇 剩余价值转化为利润和剩余价值率转化为利润率':
        - './part3/vol1/ch1/index.md'
        - '第一章 成本价格和利润': './part3/vol1/ch1/sec1.md'
        - '第二章 利润率': './part3/vol1/ch1/sec2.md'
        - '第三章 利润率和剩余价值率的关系': './part3/vol1/ch1/sec3.md'
        - '第四章 周转对利润率的影响': './part3/vol1/ch1/sec4.md'
        - '第五章 不变资本使用上的节约': './part3/vol1/ch1/sec5.md'
        - '第六章 价格变动的影响': './part3/vol1/ch1/sec6.md'
        - '第七章 补充说明': './part3/vol1/ch1/sec7.md'
      - '第二篇 利润转化为平均利润':
        - './part3/vol1/ch2/index.md'
        - '第八章 不同生产部门的资本的不同构成和由此引起的利润率的差别': './part3/vol1/ch2/sec8.md'
        - '第九章 一般利润率（平均利润率）的形成和商品价值转化为生产价格': './part3/vol1/ch2/sec9.md'
        - '第十章 一般利润率通过竞争而平均化。市场价格和市场价值。超额利润': './part3/vol1/ch2/sec10.md'
        - '第十一章 工资的一般变动对生产价格的影响': './part3/vol1/ch2/sec11.md'
        - '第十二章 补充说明': './part3/vol1/ch2/sec12.md'
      - '第三篇 利润率趋向下降的规律':
        - './part3/vol1/ch3/index.md'
        - '第十三章 规律本身': './part3/vol1/ch3/sec13.md'
        - '第十四章 起反作用的各种原因': './part3/vol1/ch3/sec14.md'
        - '第十五章 规律的内部矛盾的展开': './part3/vol1/ch3/sec15.md'
      - '第四篇 商品资本和货币资本转化为商品经营资本和货币经营资本（商人资本）':
        - './part3/vol1/ch4/index.md'
        - '第十六章 商品经营资本': './part3/vol1/ch4/sec16.md'
        - '第十七章 商业利润': './part3/vol1/ch4/sec17.md'
        - '第十八章 商人资本的周转。价格': './part3/vol1/ch4/sec18.md'
        - '第十九章 货币经营资本': './part3/vol1/ch4/sec19.md'
        - '第二十章 关于商人资本的历史考察': './part3/vol1/ch4/sec20.md'
      - '第五篇 利润分为利息和企业主收入。生息资本':
        - './part3/vol1/ch5/index.md'
        - '第二十一章 生息资本': './part3/vol1/ch5/sec21.md'
        - '第二十二章 利润的分割。利息率。“自然”利息率': './part3/vol1/ch5/sec22.md'
        - '第二十三章 利息和企业主收入': './part3/vol1/ch5/sec23.md'
        - '第二十四章 资本关系在生息资本形式上的外表化': './part3/vol1/ch5/sec24.md'
        - '第二十五章 信用和虚拟资本': './part3/vol1/ch5/sec25.md'
        - '第二十六章 货币资本的积累，它对利息率的影响': './part3/vol1/ch5/sec26.md'
        - '第二十七章 信用在资本主义生产中的作用': './part3/vol1/ch5/sec27.md'
        - '第二十八章 流通手段和资本。图克和富拉顿的见解': './part3/vol1/ch5/sec28.md'
    - '下册':
      - '第五篇 利润分为利息和企业主收入。生息资本（续）':
        - './part3/vol2/ch5/index.md'
        - '第二十九章 银行资本的组成部分': './part3/vol2/ch5/sec29.md'
        - '第三十章 货币资本和现实资本。I': './part3/vol2/ch5/sec30.md'
        - '第三十一章 货币资本和现实资本。II（续）': './part3/vol2/ch5/sec31.md'
        - '第三十二章 货币资本和现实资本。III（续完）': './part3/vol2/ch5/sec32.md'
        - '第三十三章 信用制度下的流通手段': './part3/vol2/ch5/sec33.md'
        - '第三十四章 通货原理和 1844 年英国的银行立法': './part3/vol2/ch5/sec34.md'
        - '第三十五章 贵金属和汇兑率': './part3/vol2/ch5/sec35.md'
        - '第三十六章 资本主义以前的状态': './part3/vol2/ch5/sec36.md'
      - '第六篇 超额利润转化为地租':
        - './part3/vol2/ch6/index.md'
        - '第三十七章 导论': './part3/vol2/ch6/sec37.md'
        - '第三十八章 级差地租:概论': './part3/vol2/ch6/sec38.md'
        - '第三十九章 级差地租的第一形式（级差地租 I）': './part3/vol2/ch6/sec39.md'
        - '第四十章 级差地租的第二形式（级差地租 II）': './part3/vol2/ch6/sec40.md'
        - '第四十一章 级差地租 II——第一种情况：生产价格不变': './part3/vol2/ch6/sec41.md'
        - '第四十二章 级差地租 II——第二种情况：生产价格下降': './part3/vol2/ch6/sec42.md'
        - '第四十三章 级差地租 II——第三种情况：生产价格上涨。结论': './part3/vol2/ch6/sec43.md'
        - '第四十四章 最坏耕地也有级差地租': './part3/vol2/ch6/sec44.md'
        - '第四十五章 绝对地租': './part3/vol2/ch6/sec45.md'
        - '第四十六章 建筑地段的地租。矿山地租。土地价格': './part3/vol2/ch6/sec46.md'
        - '第四十七章 资本主义地租的起源': './part3/vol2/ch6/sec47.md'
      - '第七篇 各种收入及其源泉':
        - './part3/vol2/ch7/index.md'
        - '第四十八章 三位一体的公式': './part3/vol2/ch7/sec48.md'
        - '第四十九章 关于生产过程的分析': './part3/vol2/ch7/sec49.md'
        - '第五十章 竞争的假象': './part3/vol2/ch7/sec50.md'
        - '第五十一章 分配关系和生产关系': './part3/vol2/ch7/sec51.md'
        - '第五十二章 阶级': './part3/vol2/ch7/sec52.md'

# Plugins
plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: none
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      auto_caption: false
      caption_position: bottom

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  # - pymdownx.magiclink:
  #     repo_url_shorthand: true
  #     user: squidfunk
  #     repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - css/extra.css

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/extra.js
